// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.idsi2015.gmobility.jsf;

import ch.idsi2015.gmobility.jsf.ItineraireBean;
import java.io.Serializable;

privileged aspect ItineraireBean_Roo_Serializable {
    
    declare parents: ItineraireBean implements Serializable;
    
    private static final long ItineraireBean.serialVersionUID = 1L;
    
}
