// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.idsi2015.gmobility.domain;

import ch.idsi2015.gmobility.domain.Itineraire;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Itineraire_Roo_Configurable {
    
    declare @type: Itineraire: @Configurable;
    
}
