// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.idsi2015.gmobility.domain;

import ch.idsi2015.gmobility.domain.Itineraire;

privileged aspect Itineraire_Roo_JavaBean {
    
    public String Itineraire.getTrajet() {
        return this.trajet;
    }
    
    public void Itineraire.setTrajet(String trajet) {
        this.trajet = trajet;
    }
    
}
